[project]
name = "rne"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.9.0",
    "fastapi[standard]>=0.119.0",
    "isort>=7.0.0",
    "psutil>=7.0.0",
    "scapy>=2.6.1",
]
